name: Build Client Mezi Pultosok Apk

on:
  push:
    branches: [github-actions-setup]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read version from package.json
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk-version: 21.4.7075529

      - name: Install dependencies
        run: yarn install

      - name: Modify build.gradle in react-native-os
        run: sed -i "s/compile 'com.facebook.react:react-native:+/implementation 'com.facebook.react:react-native:+/g" node_modules/react-native-os/android/build.gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build APK
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Upload file to server
        run: |
          curl -X POST "https://kisvesszosi-munka-beosztas.mypremiumhost.tech/upload?version=${{ env.VERSION }}" \
          -H "Content-Type: multipart/form-data" \
          -F "file=@android/app/build/outputs/apk/release/app-release.apk"