name: Update Package Version

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read APK_VERSION from .env
        id: read_version
        run: |
          echo "APK_VERSION=$(grep 'APK_VERSION=' .env | cut -d '=' -f 2)" >> $GITHUB_ENV

      - name: Read version from package.json
        id: read_package_version
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Check if versions match
        id: check_versions
        run: |
          if [ "${{ env.APK_VERSION }}" = "${{ env.PACKAGE_VERSION }}" ]; then
            echo "Versions match"
            echo "MATCH=true" >> $GITHUB_ENV
          else
            echo "Versions do not match"
            echo "MATCH=false" >> $GITHUB_ENV
          fi

      - name: Update package.json version
        if: env.MATCH == 'false'
        run: |
          APK_VERSION=$(echo "${{ env.APK_VERSION }}")
          jq --arg ver "$APK_VERSION" '.version = $ver' package.json > tmp.$$.json && mv tmp.$$.json package.json

      - name: Increment versionCode in build.gradle
        if: env.MATCH == 'false'
        run: |
          # Read the current versionCode
          versionCode=$(grep 'versionCode' android/app/build.gradle | awk '{print $2}')
          # Increment the versionCode
          newVersionCode=$((versionCode + 1))
          # Update the build.gradle file with the new versionCode
          sed -i "s/versionCode $versionCode/versionCode $newVersionCode/" android/app/build.gradle
          # Update the build.gradle file with the new versionName
          APK_VERSION=$(echo "${{ env.APK_VERSION }}")
          sed -i "s/versionName \".*\"/versionName \"$APK_VERSION\"/" android/app/build.gradle

      - name: Commit changes
        if: env.MATCH == 'false'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add package.json 
          git add android/app/build.gradle
          git commit -m "Synchronize version to ${{ env.APK_VERSION }} and increment versionCode to $newVersionCode"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}